Hotfix (06.01.2022)
NeonGeckoCom/neon_mq_connector pull request #39
Opened 2022-01-06 17:29 UTC by NeonKirill

Fixed order for `register_consumer()` as it broke dependencies

2022-01-07 02:35 UTC, NeonDaniel requested changes
We should have tests that reproduce any discovered issues to avoid hitting this same problem in the future

2022-01-07 02:35 UTC, NeonDaniel commented on neon_mq_connector/connector.py
>      def register_consumer(self, name: str, vhost: str, queue: str,
Add some unit tests that look like calls to this method that exist currently so we can test for similar breakage in the future

2022-01-11 19:10 UTC, NeonDaniel commented
Looks like there is a problem in new tests?
```
    def test_stable_register_consumer_args(self):
        try:
            # Required connector.register_consumer() arguments order:
            # name: str, vhost: str, queue: str,
            # callback: callable, on_error: Optional[callable] = None,
            # auto_ack: bool = True
            self.connector.register_consumer("test_consumer",
                                             self.connector.vhost,
                                             'test',
                                             self.connector.callback_func_1,
                                             self.connector.default_error_handler,
                                             False)
            self.assertIsInstance(self.connector.consumers['test_consumer'], ConsumerThread)
            self.assertEqual(self.connector.consumers['test_consumer'].queue, 'test')
            self.assertEqual(self.connector.consumers['test_consumer'].exchange, '')
        except Exception as ex:
>           self.fail(f'Registering consumer failed: ***ex***')
E           AssertionError: Registering consumer failed: 'ConsumerThread' object has no attribute 'exchange'
```

2022-01-16 18:46 UTC, NeonKirill commented
> Looks like there is a problem in new tests?
> 
> ```
>     def test_stable_register_consumer_args(self):
>         try:
>             # Required connector.register_consumer() arguments order:
>             # name: str, vhost: str, queue: str,
>             # callback: callable, on_error: Optional[callable] = None,
>             # auto_ack: bool = True
>             self.connector.register_consumer("test_consumer",
>                                              self.connector.vhost,
>                                              'test',
>                                              self.connector.callback_func_1,
>                                              self.connector.default_error_handler,
>                                              False)
>             self.assertIsInstance(self.connector.consumers['test_consumer'], ConsumerThread)
>             self.assertEqual(self.connector.consumers['test_consumer'].queue, 'test')
>             self.assertEqual(self.connector.consumers['test_consumer'].exchange, '')
>         except Exception as ex:
> >           self.fail(f'Registering consumer failed: ***ex***')
> E           AssertionError: Registering consumer failed: 'ConsumerThread' object has no attribute 'exchange'
> ```

Some issue with github environment, as locally causing no issues, omitted this check for now

2022-01-17 18:01 UTC, NeonDaniel reviewed
Just needs license header on added test file and then good to go

2022-01-20 17:46 UTC, NeonDaniel approved these changes

2022-02-07 16:30 UTC, merged